markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: Příliš hlučná samota
markdown: rdiscount

author: "XK"
atom-baseurl: "http://xukun.name"
disqus: "xukun"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About Me
    class: fa fa-user
    href: /CV.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

