markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: ||||||||X|||||| |||
markdown: rdiscount

author: "XU Kun Jacob"
atom-baseurl: "http://xukun.name"
disqus: "xukun"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: CV
    class: fa fa-user
    href: /CV.html
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

